### ISSUE TITLE
The Example

### ISSUE THREAD

**Issue by suntong** [mh-cbon/philea#2]
The Example in README, 

```
$ philea --pattern main.go "echo %fname" "echo %f" "echo %dname" "echo %d" "echo %s"
echo ./: ./
echo main.go: main.go
echo main: main
echo ./main.go: ./main.go
echo .: .
```

the output doesn't correspond with input or their definition. 
Is it only me that is confused?

**Comment by mh-cbon** [comment]
What do you mean ? 

For each 5 commands 
"echo %fname" "echo %f" "echo %dname" "echo %d" "echo %s"

there is an output,
echo ./: ./
echo main.go: main.go
echo main: main
echo ./main.go: ./main.go
echo .: .

Then, yes the display is kinda shit, in
`echo ./main.go: ./main.go`
`echo ./main.go` is the cmd being run
` ./main.go` is the result

**Comment by suntong** [comment]
>    %s, it will be replaced by the current file path.

Ok. 

>    %d, it will be replaced by the path of the directory of the current file.

So the corresponding output is  `./main.go`?

>    %dname, it will be replaced by the directory name of the current file.

The corresponding output is  `main`?

>    %f, it will be replaced by the name of the current file.
    %fname, it will be replaced by the name of the current file minus its extension.

...

**Comment by mh-cbon** [comment]
I see, yes makes sense, good catch.

It happens because in this example there is not the 
`  -S --series             Execute process in series instead of parallel.` argument

```
$ philea -S --pattern main.go "echo %fname" "echo %f" "echo %dname" "echo %d" "echo %s"
echo main: main
echo main.go: main.go
echo .: .
echo ./: ./
echo ./main.go: ./main.go
```

**Comment by suntong** [comment]
Gotya.

**Comment by mh-cbon** [comment]
i keep it open to fix it somedays.
